/* eslint-disable import/prefer-default-export */
export const films = [
  {
    name: 'Трон: Наследие',
    genre: 'Игры',
    img: '/img/films/throne.jpg',
    year: '2010',
    id: 1,
  },
  {
    name: 'Warcraft: Начало',
    genre: 'Игры',
    img: '/img/films/warcraft.jpg',
    year: '2016',
    id: 2,
  },
  {
    name: 'Пиксели',
    genre: 'Игры',
    img: '/img/films/pixels.jpg',
    year: '2015',
    id: 3,
  },
  {
    name: 'Скрытые фигуры',
    genre: 'История',
    img: '/img/films/hidden_figures.jpg',
    year: '2016',
    id: 4,
  },
  {
    name: 'Царство небесное',
    genre: 'История',
    img: '/img/films/kingdom_of_heaven.jpeg',
    year: '2005',
    id: 5,
  },
  {
    name: 'Пианист',
    genre: 'История',
    img: '/img/films/the_pianist.jpg',
    year: '2002',
    id: 6,
  },
  {
    name: 'Супернянь',
    genre: 'Комендия',
    img: '/img/films/Babysitting.jpg',
    year: '2014',
    id: 7,
  },
  {
    name: 'Круелла',
    genre: 'Комендия',
    img: '/img/films/Cruella.jpg',
    year: '2021',
    id: 8,
  },
  {
    name: 'Красное уведомление',
    genre: 'Комендия',
    img: '/img/films/red_message.jpeg',
    year: '2021',
    id: 9,
  },
  {
    name: 'Смерть на Ниле',
    genre: 'Детектив',
    img: '/img/films/death_on_the_Nile.jpeg',
    year: '2022',
    id: 10,
  },
  {
    name: 'В тени Луны',
    genre: 'Детектив',
    img: '/img/films/in_the_shadow_of_the_moon.jpg',
    year: '2019',
    id: 11,
  },
  {
    name: 'Платформа',
    genre: 'Детектив',
    img: '/img/films/platform.jpeg',
    year: '2019',
    id: 12,
  },
  {
    name: 'Дом Гуччи',
    genre: 'Драма',
    img: '/img/films/house_of_Gucci.jpeg',
    year: '2021',
    id: 13,
  },
  {
    name: 'Ла-Ла Ленд',
    genre: 'Драма',
    img: '/img/films/La_La_Land.jpg',
    year: '2016',
    id: 14,
  },
  {
    name: 'Тихий омут',
    genre: 'Драма',
    img: '/img/films/stillwater.jpg',
    year: '2021',
    id: 15,
  },
  {
    name: 'Властелин морей: На краю света',
    genre: 'Приключения',
    img: '/img/films/masterandcommander.jpg',
    year: '2003',
    id: 16,
  },
  {
    name: 'Дулитл',
    genre: 'Приключения',
    img: '/img/films/Dolittle.jpg',
    year: '2020',
    id: 17,
  },
  {
    name: 'Дюна',
    genre: 'Приключения',
    img: '/img/films/Dune.jpg',
    year: '2021',
    id: 18,
  },
];
