/* eslint-disable import/prefer-default-export */
export const series = [
<<<<<<< HEAD
  {
    name: 'Чернобыль',
    genre: 'История',
    img: '/img/series/chernobyl.jpeg',
    year: '2019',
    id: 19,
  },
  {
    name: 'Рим',
    genre: 'История',
    img: '/img/series/rome.jpeg',
    year: '2005',
    id: 20,
  },
  {
    name: 'Тюдоры',
    genre: 'История',
    img: '/img/series/tudors.jpeg',
    year: '2007',
    id: 21,
  },
  {
    name: 'Флеш',
    genre: 'Приключение',
    img: '/img/series/the_flash.jpg',
    year: '2014',
    id: 22,
  },
  {
    name: 'Ведьмак',
    genre: 'Приключение',
    img: '/img/series/the_witcher.jpeg',
    year: '2019',
    id: 23,
  },
  {
    name: 'Любов, смерть и роботы',
    genre: 'Приключение',
    img: '/img/series/Love_death_work.jpeg',
    year: '2019',
    id: 24,
  },
  {
    name: 'По ту сторону жизни',
    genre: 'Комедия',
    img: '/img/series/On_the_other_side_of_life.jpeg',
    year: '2019',
    id: 25,
  },
  {
    name: 'Космические силы',
    genre: 'Комедия',
    img: '/img/series/Space_force.jpeg',
    year: '2020',
    id: 26,
  },
  {
    name: 'Миротворец',
    genre: 'Комедия',
    img: '/img/series/peacemaker.jpeg',
    year: '2022',
    id: 27,
  },
  {
    name: 'Острые козырьки',
    genre: 'Драма',
    img: '/img/series/peaky_blinders.jpg',
    year: '2013',
    id: 28,
  },
  {
    name: 'Однажды в сказке',
    genre: 'Драма',
    img: '/img/series/once_upon_a_tale .jpeg',
    year: '2011',
    id: 29,
  },
  {
    name: 'Викинги',
    genre: 'Драма',
    img: '/img/series/vikings.jpeg',
    year: '2020',
    id: 30,
  },
  {
    name: 'Мистический квест: Пир ворона',
    genre: 'Игры',
    img: '/img/series/Feast_of_the_crow.jpg',
    year: '2020',
    id: 31,
  },
  {
    name: 'Рекорд',
    genre: 'Игры',
    img: '/img/series/high_score.jpg',
    year: '2020',
    id: 32,
  },
  {
    name: 'Аркейн',
    genre: 'Игры',
    img: '/img/series/league-_legend.jpg',
    year: '2021',
    id: 33,
  },
  {
    name: 'Люцифер',
    genre: 'Детектив',
    img: '/img/series/lucifer.jpeg',
    year: '2016',
    id: 34,
  },
  {
    name: 'Сверхъестественное',
    genre: 'Детектив',
    img: '/img/series/supernatural.jpeg',
    year: '2005',
    id: 35,
  },
  {
    name: 'Манифест',
    genre: 'Детектив',
    img: '/img/series/manifest.jpeg',
    year: '2018',
    id: 36,
  },
];
=======
    {
        name :'Чернобыль',
        genre:'История',
        img:'/img/series/chernobyl.jpeg',
        year:'2019',
        id: 19,
        country:'Великобритания',
    },
    {
        name :'Рим',
        genre:'История',
        img:'/img/series/rome.jpeg',
        year:'2005',
        id: 20,
        country:'CША',
    },
    {
        name :'Тюдоры',
        genre:'История',
        img:'/img/series/tudors.jpeg',
        year:'2007',
        id: 21,
        country:'Великобритания',
    },
    {
        name :'Флеш',
        genre:'Приключение',
        img:'/img/series/the_flash.jpg',
        year:'2014',
        id: 22,
        country:'CША',
    },
    {
        name :'Ведьмак',
        genre:'Приключение',
        img:'/img/series/the_witcher.jpeg',
        year:'2019',
        id: 23,
        country:'Великобритания',

    },
    {
        name :'Любов, смерть и роботы',
        genre:'Приключение',
        img:'/img/series/Love_death_work.jpeg',
        year:'2019',
        id: 24,
        country:'CША',
    },
    {
        name :'По ту сторону жизни',
        genre:'Комедия',
        img:'/img/series/On_the_other_side_of_life.jpeg',
        year:'2019',
        id: 25,
        country:'Канада'

    },
    {
        name :'Космические силы',
        genre:'Комедия',
        img:'/img/series/Space_force.jpeg',
        year:'2020',
        id: 26,
        country:'Канада'

    },
    {
        name :'Миротворец',
        genre:'Комедия',
        img:'/img/series/peacemaker.jpeg',
        year:'2022',
        id: 27,
        country:'CША',
    },
    {
        name :'Острые козырьки',
        genre:'Драма',
        img:'/img/series/peaky_blinders.jpg',
        year:'2014',
        id: 28,
        country:'Великобритания',
        
    },
    {
        name :'Однажды в сказке',
        genre:'Драма',
        img:'/img/series/once_upon_a_tale .jpeg',
        year:'2011',
        id: 29,
        country:'CША',
    },
    {
        name :'Викинги',
        genre:'Драма',
        img:'/img/series/vikings.jpeg',
        year:'2020',
        id: 30,
        country:'Великобритания',

    },
    {
        name :'Мистический квест: Пир ворона',
        genre:'Игры',
        img:'/img/series/Feast_of_the_crow.jpg',
        year:'2020',
        id: 31,
        country:'CША',
    },
    {
        name :'Рекорд',
        genre:'Игры',
        img:'/img/series/high_score.jpg',
        year:'2020',
        id: 32,
        country:'Япония',
    },
    {
        name :'Аркейн',
        genre:'Игры',
        img:'/img/series/league-_legend.jpg',
        year:'2021',
        id: 33,
        country:'Китай',

    },
    {
        name :'Люцифер',
        genre:'Детектив',
        img:'/img/series/lucifer.jpeg',
        year:'2016',
        id: 34,
        country:'CША'

    },
    {
        name :'Сверхъестественное',
        genre:'Детектив',
        img:'/img/series/supernatural.jpeg',
        year:'2005',
        id: 35,
        country:'Канада',
    },
    {
        name :'Манифест',
        genre:'Детектив',
        img:'/img/series/manifest.jpeg',
        year:'2018',
        id: 36,
        country:'Канада',
    },
];
>>>>>>> ab1995e9199de339ece0d240bf0e05f7048307e4
