'use strict';
const films = [
  {
    name: 'Супернянь',
    genre: 'Комедія',
    img: '/img/films/Babysitting.jpg',
    year: '2014',
  },
  {
    name: 'Червоне повідомлення',
    genre: 'Комедія',
    img: '/img/films/red_message.jpeg',
    year: '2021',
  },
  {
    name: 'Круелла',
    genre: 'Комедія',
    img: '/img/films/Cruella.jpg',
    year: '2021',
  },
  {
    name: 'Дюна',
    genre: 'Пригоди',
    img: '/img/films/Dune.jpg',
    year: '2021',
  },
  {
    name: 'Дулітл',
    genre: 'Пригоди',
    img: '/img/films/Dolittle.jpg',
    year: '2020',
  },
  {
    name: 'Господар морів : на краю Землі',
    genre: 'Пригоди',
    img: '/img/films/masterandcommander.jpg',
    year: '2003',
  },
  {
    name: 'Смерть на Нілі',
    genre: 'Детектив',
    img: '/img/films/death_on_the_Nile.jpeg',
    year: '2022',
  },
  {
    name: 'У тіні Місяця',
    genre: 'Детектив',
    img: '/img/films/in_the_shadow_of_the_moon.jpg',
    year: '2019',
  },
  {
    name: 'Платформа',
    genre: 'Детектив',
    img: '/img/films/platform.jpeg',
    year: '2019',
  },
  {
    name: 'Тихий вир',
    genre: 'Драма',
    img: '/img/films/stillwater.jpg',
    year: '2021',
  },
  {
    name: 'Ла-Ла Ленд',
    genre: 'Драма',
    img: '/img/films/La_La_Land.jpg',
    year: '2016',
  },
  {
    name: 'Дім Гуччі',
    genre: 'Драма',
    img: '/img/films/house_of_Gucci.jpeg',
    year: '2021',
  },
  {
    name: 'Warcraft: Початок',
    genre: 'Ігри',
    img: '/img/films/warcraft.jpg',
    year: '2016',
  },
  {
    name: 'Трон: Спадок',
    genre: 'Ігри',
    img: '/img/films/throne.jpg',
    year: '2010',
  },
  {
    name: 'Пікселі',
    genre: 'Ігри',
    img: '/img/films/pixels.jpg',
    year: '2015',
  },
  {
    name: 'Піаніст',
    genre: 'Історія',
    img: '/img/films/the_pianist.jpeg',
    year: '2002',
  },
  {
    name: 'Приховані фігури',
    genre: 'Історія',
    img: '/img/films/hidden_figures.jpg',
    year: '2016',
  },
  {
    name: 'Царство небесне',
    genre: 'Історія',
    img: '/img/films/kingdom_of_heaven.jpeg',
    year: '2005',
  },
];
